document.title;
console.log(document.title);
document.title = "Demo Page";
console.log(document.title);
console.log(document.scripts);
console.log(document.URL);
console.log(document.links);
console.log(document.links[0]);
document.links[0].href = "http://www.microsoft.com/learning";
document.links[0].target = "_blank";
console.log(document.head);
console.log(document.body);
console.log(document.getElementsByTagName('footer'));
console.log(document.getElementsByTagName('footer')[0]);
document.getElementsByTagName('footer')[0].innerHTML = "Demo Footer";
console.log(document.getElementsByTagName('footer')[0]);
console.log(document.getElementsByTagName('article'));
console.log(document.getElementsByClassName('demoClass'));
console.log(document.getElementById('testNav'));